
package desain_sistem;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class data_karyawan extends javax.swing.JFrame {
String sql;

    public data_karyawan() {
        initComponents();
        
        Tampilkan_Data();
       
    }
    private void Kosongkan_Form(){
        jtxkode.setEditable(true);
        jtxkode.setText(null);
        jtxnama.setText(null);
        jtxalamat.setText(null);
        jtxagama.setText(null);
        jk.setSelectedItem(null);
        jtxjabatan.setText(null);
    }
        private void Tampilkan_Data() {
            DefaultTableModel model= new DefaultTableModel();
            model.addColumn("Kode Karyawan");
            model.addColumn("Nama Karyawan");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Alamat");
            model.addColumn("Agama");
            model.addColumn("Jabatan");
            
            try {
                String sql="SELECT * FROM `karyawan`";
                java.sql.Connection conn=(Connection) koneksi.configDB();
                java.sql.Statement stm=conn.createStatement();
                java.sql.ResultSet res=stm.executeQuery(sql);
                while (res.next()){
                    model.addRow(new Object[]{
                        res.getString(1), 
                        res.getString(2),
                        res.getString(3),
                        res.getString(4),
                        res.getString(5),
                        res.getString(6)
                        });
                }
                tabkaryawan.setModel(model);
            } catch (SQLException e) {
                System.out.println("Error : " + e.getMessage());
            
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxkode = new javax.swing.JTextField();
        jtxnama = new javax.swing.JTextField();
        jtxagama = new javax.swing.JTextField();
        jtxjabatan = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        jtxcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabkaryawan = new javax.swing.JTable();
        jtxalamat = new javax.swing.JTextField();
        jk = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATA KARYAWAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 420, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Agama");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Jabatan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 60, 30));

        alamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alamat.setText("Alamat");
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nama Karyawan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("kode Karyawan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, 30));

        jtxkode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtxkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 140, 30));

        jtxnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtxnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, 30));

        jtxagama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtxagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 160, 30));

        jtxjabatan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtxjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 160, 30));

        btncari.setBackground(new java.awt.Color(255, 255, 204));
        btncari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon cari.jpg"))); // NOI18N
        btncari.setText("Search");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel1.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        btnkeluar.setBackground(new java.awt.Color(255, 255, 204));
        btnkeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keluar.jpg"))); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 110, 40));

        btnhapus.setBackground(new java.awt.Color(255, 255, 204));
        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.jpg"))); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 110, 40));

        btnbatal.setBackground(new java.awt.Color(255, 255, 204));
        btnbatal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon silang2.jpg"))); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 110, 40));

        btnedit.setBackground(new java.awt.Color(255, 255, 204));
        btnedit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit.jpg"))); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 110, 40));

        btnsimpan.setBackground(new java.awt.Color(255, 255, 204));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/simpan.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 110, 40));

        jtxcari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtxcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 190, 30));

        tabkaryawan.setBackground(new java.awt.Color(255, 204, 102));
        tabkaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabkaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabkaryawan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 610, 250));

        jtxalamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jtxalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 160, 30));

        jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jPanel1.add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 140, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/background login_1.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
     try {
        sql="DELETE FROM `karyawan` WHERE kode_karyawan='"+jtxkode.getText()+"'";
        java.sql.Connection conn=(Connection) koneksi.configDB();
        java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
        pstm.execute();
        JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
        Tampilkan_Data();
    Kosongkan_Form();
    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        dispose();
    new menu_admin().setVisible(true);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
    try {
        sql = "INSERT INTO `karyawan` VALUES ('"+jtxkode.getText()+"','"+jtxnama.getText()+"','"+jk.getSelectedItem()+"','"+jtxalamat.getText()+"','"+jtxagama.getText()+"','"+jtxjabatan.getText()+"')";
        java.sql.Connection conn=(Connection) koneksi.configDB();
        java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
        pstm.execute();
        JOptionPane.showMessageDialog(null, "proses simpan berhasil");
        Tampilkan_Data();
        Kosongkan_Form();
    }catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
     try {
        String sql = "UPDATE `karyawan` SET kode_karyawan='"+jtxkode.getText()
                +"',nama_karyawan='"+jtxnama.getText()
                +"',jenis_kelamin='"+jk.getSelectedItem()
                +"',alamat='"+jtxalamat.getText()
                +"',agama='"+jtxagama.getText()
                +"',jabatan='"+jtxjabatan.getText()
                +"' WHERE kode_karyawan ='"+jtxkode.getText()+"'";
        java.sql.Connection conn=(Connection) koneksi.configDB();
        java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
        pstm.execute();
        JOptionPane.showMessageDialog(null, "EDIT DATA BERHASIL");
        Tampilkan_Data();
        Kosongkan_Form();
    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
     Kosongkan_Form();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void tabkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabkaryawanMouseClicked
        int jTable1 = tabkaryawan.getSelectedRow();
        String a = tabkaryawan.getValueAt(jTable1, 0).toString();
        String b = tabkaryawan.getValueAt(jTable1, 1).toString();
        String c = tabkaryawan.getValueAt(jTable1, 2).toString();
        String d = tabkaryawan.getValueAt(jTable1, 3).toString();
        String e = tabkaryawan.getValueAt(jTable1, 4).toString();
        String f = tabkaryawan.getValueAt(jTable1, 5).toString();
        jtxkode.setText(a);
        jtxnama.setText(b);
        jk.setSelectedItem(c);
        jtxalamat.setText(d);
        jtxagama.setText(e);
        jtxjabatan.setText(f);
    }//GEN-LAST:event_tabkaryawanMouseClicked

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        try {
        DefaultTableModel model= new DefaultTableModel();
            model.addColumn("Kode Karyawan");
            model.addColumn("Nama Karyawan");
            model.addColumn("Jenis Kelamin");
            model.addColumn("Alamat");
            model.addColumn("Agama");
            model.addColumn("Jabatan");
        String sql="SELECT * FROM `karyawan` WHERE `kode_karyawan` like '%"+jtxcari.getText()+"%'"
                +"or `nama_karyawan`like '%"+jtxcari.getText()+"%'"+"or `jenis_kelamin`like '%"
                +""+jtxcari.getText()+"%'"+"or `alamat`like '%"+jtxcari.getText()+"%'"+"or `agama`like '%"+jtxcari.getText()+"%'"
                +"or `jabatan`like'%"+jtxcari.getText()+"%' ";
         java.sql.Connection conn=(Connection) koneksi.configDB();
                java.sql.Statement stm=conn.createStatement();
                java.sql.ResultSet res=stm.executeQuery(sql);
           while (res.next()){
                    model.addRow(new Object[]{
                        res.getString(1), 
                        res.getString(2),
                        res.getString(3),
                        res.getString(4),
                        res.getString(5)
                        });
                }
                tabkaryawan.setModel(model);
    }catch (HeadlessException | SQLException e) {
        
    }
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jk;
    private javax.swing.JTextField jtxagama;
    private javax.swing.JTextField jtxalamat;
    private javax.swing.JTextField jtxcari;
    private javax.swing.JTextField jtxjabatan;
    private javax.swing.JTextField jtxkode;
    private javax.swing.JTextField jtxnama;
    private javax.swing.JTable tabkaryawan;
    // End of variables declaration//GEN-END:variables

    
   
}      
                
    

