/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desain_sistem;

/**
 *
 * @author ACER
 */
public class menu_admin extends javax.swing.JFrame {

    /**
     * Creates new form menu_admin
     */
    public menu_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnadmin = new javax.swing.JButton();
        btnkaryawan = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnminuman = new javax.swing.JButton();
        btnmakanan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/background padang copy.jpg"))); // NOI18N

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnadmin.setBackground(new java.awt.Color(255, 255, 204));
        btnadmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnadmin.setText("Data Admin");
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });
        jPanel1.add(btnadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, 40));

        btnkaryawan.setBackground(new java.awt.Color(255, 255, 204));
        btnkaryawan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnkaryawan.setText("Data Karyawan");
        btnkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(btnkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 180, 40));

        btnkeluar.setBackground(new java.awt.Color(255, 255, 204));
        btnkeluar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon silang2.jpg"))); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, 40));

        jLabel3.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SILAHKAN PILIH");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 350, 70));

        btnminuman.setBackground(new java.awt.Color(255, 255, 204));
        btnminuman.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnminuman.setText("Data Minuman");
        btnminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminumanActionPerformed(evt);
            }
        });
        jPanel1.add(btnminuman, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 170, 40));

        btnmakanan.setBackground(new java.awt.Color(255, 255, 204));
        btnmakanan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnmakanan.setText("Data Makanan");
        btnmakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmakananActionPerformed(evt);
            }
        });
        jPanel1.add(btnmakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/aadmin.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/makanan padang.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 170, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/minuman.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 170, 150));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kaaryawan.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 180, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/blured.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
       dispose();
       new data_admin().setVisible(true);
    }//GEN-LAST:event_btnadminActionPerformed

    private void btnkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaryawanActionPerformed
        dispose();
        new data_karyawan().setVisible(true);
    }//GEN-LAST:event_btnkaryawanActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        dispose ();
        new admin_atau_pengunjung().setVisible(true);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnmakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmakananActionPerformed
    dispose();
    new desain_makanan().setVisible(true);
    }//GEN-LAST:event_btnmakananActionPerformed

    private void btnminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminumanActionPerformed
    dispose();
    new desain_minuman().setVisible(true);
    }//GEN-LAST:event_btnminumanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btnkaryawan;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnmakanan;
    private javax.swing.JButton btnminuman;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
